core/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import HomeView, agents_list, register, login_view,DashboardView,ProfileUpdateView,ProfileView

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),

    path('register/',register, name='register'),

    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page='home'
        ),
        name='logout'
    ), 
     path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('agents/',agents_list, name='agents'),

    path('leads/',  include('leads.urls', namespace="leads")),
   
 ]


leads/urls.py
from django.urls import path
from .views import  EventCreateForAdmin, EventCreateForUser,LeadCreateViewForAdmin, LeadCreateViewForUser, detail_view, lead_list, events_list, lead_update_admin, lead_update_user, LeadDeleteView


app_name = "leads"

urlpatterns = [
        path('', lead_list, name='lead_list'),


        path('create/',LeadCreateViewForUser.as_view() , name='lead_create_user'),
        path('createAd/',LeadCreateViewForAdmin.as_view() , name='lead_create_admin'),
        path('<pk>/update', lead_update_user,name='lead_update_user'),
        path('<pk>/updateAd', lead_update_admin,name='lead_update_admin'),
        path('<pk>/delete/', LeadDeleteView.as_view(), name='lead_delete'),
        path('<int:pk>/', detail_view,name='lead_detail'),





        path('events/createUs', EventCreateForUser.as_view(),name='event_create_user'),
        path('events/createAd', EventCreateForAdmin.as_view(),name='event_create_admin'),


        
       
        path('events_list', events_list, name='events_list'),


       


        
]

leads/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from datetime import datetime 



class Prospect(models.Model):
    PasContacte= 'Pas contacté'
    ARelancer = 'A relancer'
    EnCours = 'En cours'
    PasInteresse= 'Pas intéressé'
    DossierAnnule = 'Dossier Annulé'
    Signe = 'Signé'

    STATUS = (
        (PasContacte, 'Pas contacté'),
        (ARelancer, 'A relancer'),
        (EnCours, 'En cours'),
        (PasInteresse, 'Pas intéressé'),
        (DossierAnnule,'Dossier Annulé'),
        (Signe,'Signé'),
    )

    Nom = models.CharField(max_length=20)
    Prénom = models.CharField(max_length=20)
    Email = models.EmailField()
    NumeroDeTelephone = models.CharField(max_length=20)
    Age = models.IntegerField(default=0)
    Marié = models.BooleanField(default=False)
    NBEnfants = models.IntegerField(default=0)
    Agent = models.ForeignKey(settings.AUTH_USER_MODEL,null=True, blank=True, on_delete=models.SET_NULL)
    Profession = models.CharField(max_length=20)
    RevenuAnnuel = models.FloatField(default=0)
    Adresse = models.CharField(max_length=20)
    
    créeLe = models.DateField(auto_now_add=True)
    
    status = models.CharField(max_length=25, choices=STATUS, default=PasContacte)

    def __str__(self):
        return f"{self.Nom} {self.Prénom}"


class Event(models.Model):
    Evaluation = 'Evaluation'
    Relance = 'Relance'
    Vente = 'Vente'
    RemiseDeContrat = 'RemiseDeContrat'
    Recouvrement = 'Recouvrement'

    NATURE = (
        (Evaluation, 'Evaluation'),
        (Relance,'Relance'),
        (Vente, 'Vente'),
        (RemiseDeContrat, 'RemiseDeContrat'),
        (Recouvrement,'Recouvrement'),
    )

    Intéressé = 'Intéressé'
    NonIntéressé = 'NonIntéressé'
    ARevoir = 'A revoir'
    FixationDeRDV= 'FixationDeRDV'
    Recommandation= 'Recommandation'

    RESULTATS = (
        (Intéressé, 'Intéressé'),
        (NonIntéressé,'NonIntéressé'),
        (ARevoir, 'A revoir'),
        (RemiseDeContrat, 'RemiseDeContrat'),
        (Recommandation,'Recommandation'),
    )

    
    
    Prospect = models.ForeignKey(Prospect,null=True, on_delete=models.CASCADE)

    NatureDeVisite = models.TextField(choices=NATURE, default=Evaluation, blank=False)
    ResultatDeVisite = models.TextField(choices=RESULTATS, default=Evaluation, blank=False)



    DateDeProspection = models.DateField(default=datetime.now())

    Proposition = models.BooleanField(default=False, blank= True)
        
    PerformanceRetraitePlus = 'Performance Retraite Plus'
    MixteSimple = 'Mixte simple'
    MixteDynamique = 'Mixte Dynamique'
    RenteEducation= 'Rente Education'
    CapitalisationIndividuelle= 'Capitalisation Individuelle'
    TYPES = (
        (PerformanceRetraitePlus, 'Performance Retraite Plus'),
        (MixteSimple,'Mixte Simple'),
        (MixteDynamique, 'Mixte Dynamique'),
        (RenteEducation, 'Rente Education'),
        (CapitalisationIndividuelle,'Capitalisation Individuelle'),
    )
    TypeContratOffert = models.TextField(choices=TYPES, blank=True)

    DureeContratOffert = models.IntegerField(default=0, blank=True)





    
   


    

    



leads/forms.py
from ast import Not
from dataclasses import fields
from django import forms
from accounts.models import User
from .models import Prospect



from django.forms import ModelForm, DateInput
from .models import Event

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Prospect
        exclude = ['Agent']
        fields = '__all__'


class LeadModelAdminForm(forms.ModelForm):
    class Meta:
        model = Prospect
        fields = '__all__'
    def __init__(self, *args, **kwargs):
      super(LeadModelAdminForm, self).__init__(*args, **kwargs)
      self.fields['Agent'].queryset = User.objects.filter(is_agent = True)

class LeadUpdateForm(forms.ModelForm):
    class Meta:
        model = Prospect
        
        fields = [
          'status',
          'Agent',
        ]
    def __init__(self, *args, **kwargs):
        super(LeadUpdateForm, self).__init__(*args, **kwargs)
        self.fields['Agent'].queryset = User.objects.filter(is_agent = True)

class LeadUpdateFormUser(forms.ModelForm):
    class Meta:
        model = Prospect
        
        fields = [
          'status',
        ]
    def __init__(self, *args, **kwargs):
        super(LeadUpdateFormUser, self).__init__(*args, **kwargs)
    









from django.forms import ModelForm, DateInput
from .models import Event

YEARS= [x for x in range(2022,2030)]


class EventForm(ModelForm):
  Prospect = forms.ModelChoiceField(
        queryset=Prospect.objects.none()
    )
  Proposition = forms.BooleanField(required=False)

  class Meta:
    model = Event
    

    fields = '__all__'
    
  def __init__(self,*args,**kwargs):
    user = kwargs.pop('Agent')

    forms.ModelForm.__init__(self, *args, **kwargs)
    self.fields['Prospect'].queryset = Prospect.objects.filter(Agent = user)
   
 
    

class EventFormAdmin(ModelForm):

  class Meta:
    model = Event
    fields = '__all__'
    
    #DateDeProspection = forms.DateField(label='DateDeProspection', widget=forms.SelectDateWidget(years=YEARS))
  def __init__(self, *args, **kwargs):
    super(EventFormAdmin, self).__init__(*args, **kwargs)

    # input_formats parses HTML5 datetime-local input to datetime field
    #self.fields['Agent'].queryset = User.objects.filter(is_agent = True)
    #self.fields['DateDeProspection'].input_formats = ('%Y-%m-%dT%H:%M',)

leads/views.py
from multiprocessing import context
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, DeleteView, FormView
from leads.filters import LeadFilter

from .models import Prospect, Event
from .forms import EventFormAdmin, LeadModelForm, LeadModelAdminForm, EventForm, LeadUpdateForm, LeadUpdateFormUser
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render


class LeadCreateViewForUser(LoginRequiredMixin,CreateView):
    template_name = "leads/lead_create.html"
    
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.Agent = self.request.user
        
        form.save()
        
        messages.success(self.request, "You have successfully created a lead")
        return super(LeadCreateViewForUser, self).form_valid(form)



class LeadCreateViewForAdmin(LoginRequiredMixin,CreateView):
    template_name = "leads/lead_create.html"
    
    form_class = LeadModelAdminForm

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        form.save()
        
        messages.success(self.request, "You have successfully created a lead")
        return super(LeadCreateViewForAdmin, self).form_valid(form)



@login_required
def lead_update_admin(request, pk,*args):
    lead = Prospect.objects.get(id=pk)
    form = LeadUpdateForm(instance=lead)
    if request.method == "POST":
        form = LeadUpdateForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('leads:lead_detail', args=[lead.id]))

    
    context = {
        "form": form,
        "lead": lead
    }
    return render(request, "leads/lead_update.html", context)

@login_required
def lead_update_user(request, pk):
    lead = Prospect.objects.get(id=pk)
    form = LeadUpdateFormUser(instance=lead)
    if request.method == "POST":
        form = LeadUpdateFormUser(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form,
        "lead": lead
    }
    return render(request, "leads/lead_update.html", context)

class LeadDeleteView(LoginRequiredMixin,DeleteView):
    model = Prospect
    template_name = "leads/lead_confirm_delete.html"

    def get_success_url(self):
        return reverse("leads:lead_list")

@login_required
def detail_view(request, pk):
    lead = get_object_or_404(Prospect, id=pk)

    events = Event.objects.filter(Prospect = lead)
    last_events = Event.objects.filter(Prospect =  lead).last()


    context = {
        "lead": lead,
        "events": events,
        "last_events": last_events

    }
                 
    return render(request, "leads/detail.html", context)



def last_c(request,pk):
    lead = get_object_or_404(Prospect, id=pk)
    last_events = Event.objects.filter(Prospect =  lead).last()
    return last_events



        


@login_required
def lead_list(request):
    if request.user.is_agent:
       leads = Prospect.objects.filter(Agent=request.user)
    else: leads = Prospect.objects.all()
    

    myFilter = LeadFilter(request.GET, queryset= leads)
    leads = myFilter.qs
    
    context = {
        "leads": leads,
        "myFilter": myFilter,
    }
    return render(request, "leads/lead_list.html", context)











class EventCreateForAdmin(LoginRequiredMixin,CreateView):
    template_name = "leads/event_create.html"
    
    form_class = EventFormAdmin

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        form.save()
        
        messages.success(self.request, "You have successfully created an event")
        return super(EventCreateForAdmin, self).form_valid(form)



class EventCreateForUser(LoginRequiredMixin,FormView):
    template_name = "leads/event_create.html"
    
    form_class = EventForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['Agent'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        event = form.save(commit=False)
        
        event.Prospect.Agent = self.request.user
        
        form.save()
        
        messages.success(self.request, "You have successfully created a lead")
        return super(EventCreateForUser, self).form_valid(form)



@login_required
def events_list(request):
    if request.user.is_agent:
        events = Event.objects.filter(Agent=request.user)
    else: events = Event.objects.all()
    context = {
        "events": events
    }
    return render(request, "leads/events_list.html", context)



   







templates/leads/calendar.html
{% extends 'base.html' %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
                

        <!-- Main Content Here -->
        {% include 'events_cal/event.html' %} <---

        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/leads/detail.html
{% extends "base.html" %}

{% block content %}

<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'leads:lead_list' %}">Prsopects</a></li>
                <li class="breadcrumb-item active" aria-current="page">Détails du prospect {{lead.Nom}} {{lead.Prénom}}</li>
               </ol>
            </nav>
            <div class="btn-group" role="group" aria-label="Basic example">
              <a href="{% url 'leads:lead_update_admin' lead.pk %}" class="btn btn-outline-info btn-sm"><i class="fa-sm text-white-50"></i> Mettre a jour</a> 
              <a href="{% url 'leads:lead_delete' lead.pk %} "class="btn btn-outline-danger btn-sm"><i class="fa-sm text-white-50"></i> Supprimer</a> </td>
            </div>
        </div>        

        <!-- Main Content Here -->
        
        <div class="card shadow mb-4">
        

            
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead class="thead-info">
                    <tr>
                      <th>Nom du prospect</th>
                      <th>Email</th>
                      <th>Numero de téléphone</th>
                      <th>Age</th>

                      <th>Marié</th>
                      <th>Nombre d'enfants</th>
                      <th>Profession</th>
                      <th>Crée le</th>
                      <th>Revenu Annuel</th>
                      <th>Status</th>

                      {% if request.user.is_admin%}
                      <th>Agent</th>
                      {% endif%}
                      <th> </th>

                    </tr>
                  </thead>
                  
                  <tbody>
                    <tr>
                      <td>{{ lead.Nom}} {{ lead.Prénom }}</td>
                      <td>{{ lead.Email}}</td>
                      <td>{{ lead.NumeroDeTelephone }}</td>
                      <td>{{ lead.Age}}</td>
                      <td>{{ lead.Marié|yesno:"Oui,Non" }}</td>
                      <td>{{ lead.NBEnfants }}</td>
                      <td>{{ lead.Profession }}</td>
                      <td>{{ lead.créeLe }}</td>

                      <td>{{ lead.RevenuAnnuel }} TND</td>
                      <td>{{ lead.status }}</td>
                      <td> {{ lead.Agent.username}} </td>
                      <td> {{last_events.TypeContratOffert}} </td>

       

                    </tr>
                   </tbody>


                </table>
              </div>
            </div>
          </div>


          <div class="card-body">
              <h3><span class="badge badge-secondary">Table des visites</span></h3>
              <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nature de visite</th>
                      <th>Date de prospection</th>
                      <th>Resultat de visite</th>
                      <th>Type contrat offert</th>
                      <th>Duree contrat offert</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    {% for event in events %}

                    <tr>
                      <td>{{ event.NatureDeVisite }}</td>
                      <td>{{ event.DateDeProspection}}</td>
                      <td>{{ event.ResultatDeVisite }}</td>
                      <td>{{ event.TypeContratOffert }}</td>
                      <td>{{ event.DureeContratOffert }}</td>
                    </tr>
                   </tbody>
                  {% empty %}

                        <p>Pas d'évenements</p>

                  {% endfor %}
                </table>
              </div>
            </div>
          
          
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/leads/event_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'leads:lead_list' %}">Prsopects</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ajout de visite</li>
               </ol>
            </nav>
        </div>  
    <!-- Main Content Here -->
         <form method="POST">
            <div class="form-group">
               {% csrf_token %}
               {{ form|crispy}}
             </div>
            <button type="submit" class="btn btn-primary">Create event</button>
         </form>
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}


templates/leads/lead_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
           <form method="post">{% csrf_token %}
                <h1 class="h3 mb-0 text-gray-800">vous êtes sûr de vouloir supprimer le prospect  "{{ object }}"?</h1>
                <input type="submit" value="Confirmer" class="btn btn-danger">
                <input type="submit" value="Revenir en arriére" class="btn btn-primary" href="{% url 'leads:lead_list' %}">



            </form>
        </div>          
        <!-- Main Content Here -->
        
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/leads/lead_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'leads:lead_list' %}">Prsopects</a></li>
                <li class="breadcrumb-item active" aria-current="page">Création de prospect</li>
               </ol>
            </nav>
        </div>  
    <!-- Main Content Here -->
         <form method="POST">
            <div class="form-group">
               {% csrf_token %}
               {{ form|crispy}}
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
         </form>
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <h1 class="h3 mb-0 text-gray-800">Prospects</h1>
        </div>        

        <!-- Main Content Here -->
        
        <div class="card shadow mb-4">
            {% if request.user.is_agent %}
              <a href="{% url 'leads:lead_create_user' %} "class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" ><i class="fas fa-plus fa-sm text-white-50"></i> Creer un prospect</a>
            {% endif%}
              
            {% if request.user.is_admin %}
              <a href="{% url 'leads:lead_create_admin' %} " class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" ><i class="fas fa-plus fa-sm text-white-50"></i> Creer un prospect</a>
            {% endif%}
            {% if request.user.is_agent %}
              <a href="{% url 'leads:event_create_user' %} " class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm" ><i class="fas fa-plus fa-sm text-white-50"></i> Ajouter une visite</a>
            {% endif %}
            {% if request.user.is_admin%}
              <a href="{% url 'leads:event_create_admin' %} " class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm" ><i class="fas fa-plus fa-sm text-white-50"></i> Ajouter une visite</a>
            {% endif %}
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <br>
              </br>

             <form method="GET">
             <div class="form-group">
               {% csrf_token %}
               {{ myFilter.form}}
              <button type="submit" class="btn btn-link btn-sm">Filtrer</button>
              
             </div>
            </form>

            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr> 
                      <th> ID </th>
                      <th>Nom</th>
                      <th>Prénom</th>
                      <th>Email</th>
                      <th>Numero de téléphone</th>
                      <th>Age</th>
                      <th> Marié </th>
                      <th>Status</th>
                                            <th> Agent </th>
                      <th> details </th>
 



                    </tr>
                  </thead>
                  
                  <tbody>

                    {% for lead in leads%}

                    <tr>
                      <td> {{lead.id }} </td>
                      <td>{{ lead.Nom}}</td>
                      <td>{{ lead.Prénom }}</td>
                      <td>{{ lead.Email}}</td>
                      <td>{{ lead.NumeroDeTelephone }}</td>
                      <td>{{ lead.Age}}</td>
                      <td>{{ lead.Marié|yesno:"Oui,Non" }}</td>
                      <td>{{ lead.status }}</td>
                      
                      <td>{{ lead.Agent.username }}</td>
              
                      <td><a href="{% url 'leads:lead_detail' lead.pk %}"class="badge badge-primary" >Détails</a> </td>

                     {% endfor %}
                    



                  

                  </tbody>

                </table>
                
              </div>
            </div>
          </div>
          
          
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/leads/lead_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="text-center">
          <a class="small" href="{% url 'leads:lead_list' %}">Get back to leads</a>
        </div>
    <!-- Main Content Here -->
         <form method="POST">
            <div class="form-group">
               {% csrf_token %}
               {{ form|crispy}}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
         </form>
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}