core/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import HomeView, agents_list, register, login_view,DashboardView,ProfileUpdateView,ProfileView

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),

    path('register/',register, name='register'),

    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page='home'
        ),
        name='logout'
    ), 
     path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('agents/',agents_list, name='agents'),

    path('leads/',  include('leads.urls', namespace="leads")),
   
 ]


leads/urls.py
from django.urls import path
from .views import  EventCreateForAdmin, EventCreateForUser,LeadCreateViewForAdmin, LeadCreateViewForUser, detail_view, lead_list, events_list, lead_update_admin, lead_update_user, LeadDeleteView


app_name = "leads"

urlpatterns = [
        path('', lead_list, name='lead_list'),


        path('create/',LeadCreateViewForUser.as_view() , name='lead_create_user'),
        path('createAd/',LeadCreateViewForAdmin.as_view() , name='lead_create_admin'),
        path('<pk>/update', lead_update_user,name='lead_update_user'),
        path('<pk>/updateAd', lead_update_admin,name='lead_update_admin'),
        path('<pk>/delete/', LeadDeleteView.as_view(), name='lead_delete'),
        path('<int:pk>/', detail_view,name='lead_detail'),





        path('events/createUs', EventCreateForUser.as_view(),name='event_create_user'),
        path('events/createAd', EventCreateForAdmin.as_view(),name='event_create_admin'),


        
       
        path('events_list', events_list, name='events_list'),


       


        
]

templates/agents_list.html
{% extends "base.html" %}

{% block content %}

<!-- Begin Page Content -->
    <div class="container-fluid">
        {% if request.user.is_admin %}

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <h1 class="h3 mb-0 text-gray-800">Prospects</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Create prospect</a>
          </div>        

        <!-- Main Content Here -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Company Listing</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Username</th>
                      <th>Email</th>
                      <th>Phone number:</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    {% for User in agents%}
                    <tr>
                      <td>{{ User.username }}</td>
                      <td>{{ User.email }}</td>
                      <td>{{ User.phonenumber}}</td>
                    </tr>
                    {% endfor %}
                   </tbody>
                  
                </table>
              </div>
            </div>
          </div>
          
          
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
     {% endif %}

        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/base.html
{% load static %}
{% load crispy_forms_tags %} 
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Django CRM Project</title>

  <!-- Custom fonts for this template-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />

  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <!-- Date Time Picker CSS -->

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-white sidebar sidebar-muted alert-secondary accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center">
        <img src="{% static 'img/logo.jpg' %}" style="position: fixed;
  bottom: 625px;
  left: 0px;
  width: 225px;
  ">
      </a>
      
      <!-- Divider -->


      <!-- Divider -->
       
      <!-- Nav Item - Dashboard -->
      
      
      

      <!-- Divider -->

      <!-- Nav Item - Companies -->
        

      <li class="nav-item">
        <a class="nav-link">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>D</span></a>
      <div class="text-center">
            <h1 class="alert alert-secondary" style="width:220px;height:60px;font-size: 107%;" >{{ date }} </h1>
        </div>
      </li>
      <li class="nav-item" >
        <a class="nav-link" href="{% url 'dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt" style="color:midnightBlue;"></i>
          <span style="color:midnightBlue;">Dashboard</span></a>

      </li>

      
       <li class="nav-item">
        <a class="nav-link" href="{% url 'leads:lead_list' %} ">
          <i class="fas fa-fw fa-chart-area" style="color:navy;"></i>
          <span style="color:navy;">Prospects</span></a>
      </li>

    
      
      {% if request.user.is_admin %}
      <!-- Nav Item - Contact -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'agents' %}">
          <i class="fas fa-fw fa-table" style="color:navy;"></i>
          <span style="color:navy;">Liste des agents</span></a>
      </li>
      {% endif %}

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">
          <i class="fas fa-fw fa-user" style="color:navy;"></i>
          <span style="color:navy;">Profile</span></a>
      </li>

      

      <!-- Nav Item - Logout -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          <i class="fas fa-fw fa-sign-out-alt alert-danger"></i>
          <span style="color:navy;">Logout</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        {% include 'messages.html' %}

        {% block content %}  {% endblock content %}
        
      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  {% block script %}  {% endblock script %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>

  <!-- Date Time Picker JS -->
  <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script> 

  <script>
    $( function() {
        // $( "#id_birth_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        // $( "#id_birth_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        $( "#id_birth_date" ).datepicker({ dateFormat: 'yy-mm-dd' }).attr("autocomplete", "off") ;
    });
  </script>
  <!-- Date Time Picker JS -->

  <!-- Phone Mask JS -->
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script> 

  <script>
    //(xxx) xxx-xxxx format code
    $(document).ready(function () {
        $('#id_phone_number').usPhoneFormat({
            format: '(xxx) xxx-xxxx',
        });   
    });
  </script>
  <!-- Phone Mask JS -->

</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        </div>          

        <!-- Main Content Here -->
          <div class="row">

            <!-- Company Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Companies</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">4,083</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-home fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Contact Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Contacts</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18,002</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/example.html
{% extends 'base.html' %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Hello Everyone</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
        </div>          

        <!-- Main Content Here -->
        
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CRM - Home</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-warning">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block">
                <img src="{% static 'img/django-crm-home.png' %}" class="rounded" alt="Cinque Terre">
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome To Django CRM!</h1>
                  </div>
                  <a href="{% url 'register' %}" class="btn btn-danger btn-block btn-lg">Register / Sign Up</a>
                  <br>
                  <a href="{% url 'login' %}" class="btn btn-primary btn-block btn-lg">Login</a>
                  
                  
                  <hr>
                  <div class="text-center">
                    <a class="small" href="https://www.youtube.com/playlist?list=PLSPMgrv4IuJ4WLURdlzKNx4sgsyqW8d5q" target="_blank">Learn to create this CRM - Youtube</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="https://studygyaan.com/build-django-crm-project-from-scratch" target="_blank">StudyGyaan & ProfessionalCipher</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/login.html
{% load static %}
{% load crispy_forms_tags %} 

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author">

  <title>Django CRM - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block">
                <img src="{% static 'img/django-crm-home.png' %}" class="rounded" alt="Cinque Terre">
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                    {% if messages %}
                    <p>{{ messages }}</p>
                   {% endif %}
                  <form method="POST">
                    {% csrf_token %}
                    {{form | crispy}}
                    <button type="submit" class="btn btn-success btn-block">Login</button>
                  </form>
                  <hr>
                  
                  <div class="text-center">
                    <a class="small" href="{% url 'register' %}">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'home' %}">Home</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="https://www.youtube.com/playlist?list=PLSPMgrv4IuJ4WLURdlzKNx4sgsyqW8d5q" target="_blank">Learn to create this CRM - Youtube</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="https://studygyaan.com/build-django-crm-project-from-scratch" target="_blank">StudyGyaan & ProfessionalCipher</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/profile-update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Profile Update</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Update Your Profile!</h1>
                  </div>
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{user_form | crispy}}
                    <button type="submit" class="btn btn-success btn-block">Update</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'profile' %}">Back</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %} 

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Profile</h1>
        </div>          

        <!-- Main Content Here -->
        <div class="row">
          <div class="col-lg-2"></div>
          <div class="card o-hidden border-0 shadow-lg my-5 col-lg-5">
            <div class="card-body">
                <h2>{{user.first_name}} {{user.last_name}}</h2>
                <p><strong>Username: </strong> {{user.username}} </p>
                <p><strong>Email: </strong> {{user.email}} </p>
                <p><strong>Phone Number: </strong> {{user.phonenumber}} </p>
                <p><strong>Admin: </strong> {{user.is_admin}} </p>
                <p><strong>Agent </strong> {{user.is_agent}} </p>

 
                <a href="{% url 'profile-update' %}" class="btn btn-sm btn-primary shadow-sm">Update Profile</a>
            </div>
          </div>
        </div>
        
        
        
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/register.html
{% load static %}

{% load crispy_forms_tags %} 
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Django CRM - Register</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-2 d-none d-lg-block"></div>
          <div class="col-lg-8">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
              <hr>
              
              <div class="text-center">
                <a class="small" href="{% url 'login' %}">Already have an account? Login!</a>
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'home' %}">Home</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>